<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="H-ElFekey-Laptop" failures="1" tests="4" name="Test2" time="22.611" errors="0" timestamp="2023-06-29T09:52:03 EET">
  <testcase classname="Tests.testing2" name="test1" time="4.087">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="Tests.testing2" name="tc5" time="11.766"/>
  <testcase classname="Tests.testing2" name="tc4" time="13.018"/>
  <testcase classname="Tests.testing2" name="test1" time="3.597">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Tests.testing2.test1(testing2.java:40)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
</testsuite> <!-- Test2 -->
